import { ReactNode } from 'react';
import './globals.css';

import { Metadata } from 'next';
import Navigation from './components/navigation';
import { inter } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='en'>
      <body className={(inter.className, 'm-6 mb-24')}>
        {children}
        <Navigation />
      </body>
    </html>
  );
};

export default RootLayout;
