import { Metadata } from 'next';
import { ReactNode } from 'react';

import BackButton from './components/BackButton';
import Navigation from './components/Navigation';
import Providers from './components/provider';
import { inter } from './fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='en'>
      <Providers>
        <body className={(inter.className, 'm-8')}>
          <BackButton />
          {children}
          <Navigation />
        </body>
      </Providers>
    </html>
  );
};

export default RootLayout;
