import { ReactNode } from 'react';
import './globals.css';

import { Metadata } from 'next';
import { darkGrotesque } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang='en'>
      <body className={darkGrotesque.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
